POST  http://localhost:3000/campaigns
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJSS3FkTFREZnl4SnVUMW9aVmd5MVFsaEdwMWRQRGxTSi0tdFFPVU1ka3hrIn0.eyJleHAiOjE2ODU4MTc2ODQsImlhdCI6MTY4NTgxNzM4NCwianRpIjoiOGEzZWMwYTEtZDJhNi00NTgzLThmNzktMTg1OTU1ODU4ZjIyIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9wcm92aWRlciIsImF1ZCI6ImVtYWlsbiIsInN1YiI6IjczZmFiMTI5LTdjN2ItNDQxNC1hNjkzLTEwN2YyNDVkM2QzMiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImVtYWlsbiIsInNlc3Npb25fc3RhdGUiOiI5MmIzMzc5My1iNDc4LTQyNzMtOGI2Ny00MjRjYmViZGQ1MmUiLCJzY29wZSI6IiIsInNpZCI6IjkyYjMzNzkzLWI0NzgtNDI3My04YjY3LTQyNGNiZWJkZDUyZSJ9.NGJ7LTaNk3sDLN6nkINYt5yzIzKANyYVdTwL8jul74xMaf2eT04KJKKQN-RMIHGWCbNlEMfoLbvZIGQ6aeZ788GCacTUM3Fal2yRVIuKkUcSKBrBNydYMAulyc4Xsj_vCA8LJahW95p6h1hpCouDpjzcqpEb_IWUy0ylRxieKzx1cVBfPv6fEo9Umpj4eSRgw0iclszjf_o1nwFjZOpCZ_EOUN3KuZTFwi9Dgk22ZMt7y52jo2-q_TX5LTlvVvNl_DSBMYolkaMkWEiuCAVT0YqpDq_FVuoTvVdeZlT9fa4s0Q2lCMjxnyVnhM3BN67C6fMlj_eVJxJqbkJa7P0eLQ

{
    "Name": "change",
    "Content": "change password",
	"emails":  ["henrique@teste.com.br", "henrique2@teste.com.br", "henrique@teste.com.br"]
}

###

GET http://localhost:3000/campaigns/cgomb2mgualj7v56gb7g

###

PATCH http://localhost:3000/campaigns/cancel/cghnsnuguall070lv0m0

###

DELETE http://localhost:3000/campaigns/delete/cgkqh16guall0e775op0

###
POST http://localhost:8080/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailn&username=salmeidabatista@gmail.com&password=123456&grant_type=password

