POST  http://localhost:3000/campaigns

{
    "Name": "change",
    "Content": "change password",
	"emails":  ["henrique@teste.com.br", "henrique2@teste.com.br", "henrique@teste.com.br"]
}

###

GET http://localhost:3000/campaigns/cgkq96mgualjrc3e1blg

###

PATCH http://localhost:3000/campaigns/cancel/cghnsnuguall070lv0m0

###

DELETE http://localhost:3000/campaigns/delete/cgj2ejegualk0r0i8pd0